# Uncomment the next line to define a global platform for your project
 platform :ios, ‘8.0’

target 'Citimate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'AlamofireImage'
pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
  # Pods for Citimate
end
